    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kaibur-tasks-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: kaibur-tasks
      template:
        metadata:
          labels:
            app: kaibur-tasks
        spec:
          containers:
            - name: kaibur-tasks
              image: backend-springboot:latest  # Replace with your Docker image name
              ports:
                - containerPort: 8080
       