version: '3.8'

services:
  backend:
    image: backend-springboot
    container_name: backend-application
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017/taskdb
    networks:
      - spring-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
